runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: quantumleap.app

libraries:
- name: jinja2
  version: latest